apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webphone.fullname" . }}-backend-config
data:
  PORT: {{ .Values.backend.port | quote }}
  DB_HOST: {{ .Values.backend.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.backend.env.DB_PORT | quote }}
  DB_NAME: {{ .Values.backend.env.DB_NAME | quote }}
  DB_USER: {{ .Values.backend.env.DB_USER | quote }}
  DEFAULT_ADMIN_EMAIL: {{ .Values.backend.env.DEFAULT_ADMIN_EMAIL | quote }}
  FREESWITCH_HOST: {{ .Values.backend.env.FREESWITCH_HOST | quote }}
  FREESWITCH_PORT: {{ .Values.backend.env.FREESWITCH_PORT | quote }}
  FREESWITCH_RECORDINGS_PATH: {{ .Values.backend.env.FREESWITCH_RECORDINGS_PATH | quote }}
  FREESWITCH_GATEWAY_PATH: {{ .Values.backend.env.FREESWITCH_GATEWAY_PATH | quote }}
  FREESWITCH_EXTERNAL_SIP_IP: {{ .Values.backend.env.FREESWITCH_EXTERNAL_SIP_IP | quote }}
  BOOTSTRAP_DEFAULTS: {{ .Values.backend.env.BOOTSTRAP_DEFAULTS | quote }}
