apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webphone.fullname" . }}-laravel-config
data:
  APP_ENV: {{ .Values.laravel.env.APP_ENV | quote }}
  APP_DEBUG: {{ .Values.laravel.env.APP_DEBUG | quote }}
  DB_CONNECTION: {{ .Values.laravel.env.DB_CONNECTION | quote }}
  DB_HOST: {{ .Values.laravel.env.DB_HOST | quote }}
  DB_PORT: {{ .Values.laravel.env.DB_PORT | quote }}
  DB_DATABASE: {{ .Values.laravel.env.DB_DATABASE | quote }}
  DB_USERNAME: {{ .Values.laravel.env.DB_USERNAME | quote }}
  DB_PASSWORD: {{ .Values.laravel.env.DB_PASSWORD | quote }}
  BACKEND_URL: {{ .Values.laravel.env.BACKEND_URL | quote }}
  BACKEND_INTERNAL_TOKEN: {{ .Values.laravel.env.BACKEND_INTERNAL_TOKEN | quote }}
